// <auto-generated />
using System;
using IndkoebsGenieBackend.Database.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndkoebsGenieBackend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndkoebsGenieBackend.Database.Entities.GroceryList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GroceryLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Min første liste",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Min anden liste",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("IndkoebsGenieBackend.Database.Entities.ProductItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("GroceryListId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroceryListId", "IsCompleted");

                    b.ToTable("ProductItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            GroceryListId = 1,
                            IsCompleted = false,
                            Name = "Mælk",
                            Notes = "Letmælk",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            GroceryListId = 1,
                            IsCompleted = false,
                            Name = "Brød",
                            Notes = "Fuldkorn",
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("IndkoebsGenieBackend.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Admin Vej 1",
                            City = "København",
                            Email = "admin@mail.com",
                            FirstName = "Admin",
                            LastName = "One",
                            Password = "$2b$12$U4g5ba6EWpUaAt9CVWAgT./XXUjs3fKjpAsawmqjvvYySgrwUy1.6",
                            PostalCode = 2500,
                            Region = "København",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hovedgaden 10",
                            City = "Roskilde",
                            Email = "admin2@mail.com",
                            FirstName = "Admin",
                            LastName = "Two",
                            Password = "$2b$12$U4g5ba6EWpUaAt9CVWAgT./XXUjs3fKjpAsawmqjvvYySgrwUy1.6",
                            PostalCode = 4000,
                            Region = "Sjælland",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Test Vej 2",
                            City = "Aarhus",
                            Email = "testmail@mail.com",
                            FirstName = "Børge",
                            LastName = "Jeppensen",
                            Password = "$2b$12$YxbU0hgrY1aBwVsMLmVdBeScgC1rAtIc1ScvuZIS5zjzDBUyMKK9.",
                            PostalCode = 8000,
                            Region = "Jylland",
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Østerbrogade 45",
                            City = "København",
                            Email = "mette.larsen@mail.com",
                            FirstName = "Mette",
                            LastName = "Larsen",
                            Password = "$2b$12$YxbU0hgrY1aBwVsMLmVdBeScgC1rAtIc1ScvuZIS5zjzDBUyMKK9.",
                            PostalCode = 2100,
                            Region = "Hovedstaden",
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Algade 12",
                            City = "Aalborg",
                            Email = "jonas.poulsen@mail.com",
                            FirstName = "Jonas",
                            LastName = "Poulsen",
                            Password = "$2b$12$YxbU0hgrY1aBwVsMLmVdBeScgC1rAtIc1ScvuZIS5zjzDBUyMKK9.",
                            PostalCode = 9000,
                            Region = "Nordjylland",
                            Role = 0
                        },
                        new
                        {
                            Id = 6,
                            Address = "Vestergade 7",
                            City = "Odense",
                            Email = "sofie.nielsen@mail.com",
                            FirstName = "Sofie",
                            LastName = "Nielsen",
                            Password = "$2b$12$YxbU0hgrY1aBwVsMLmVdBeScgC1rAtIc1ScvuZIS5zjzDBUyMKK9.",
                            PostalCode = 5000,
                            Region = "Syddanmark",
                            Role = 0
                        },
                        new
                        {
                            Id = 7,
                            Address = "Byvej 3",
                            City = "Silkeborg",
                            Email = "anders.madsen@mail.com",
                            FirstName = "Anders",
                            LastName = "Madsen",
                            Password = "$2b$12$YxbU0hgrY1aBwVsMLmVdBeScgC1rAtIc1ScvuZIS5zjzDBUyMKK9.",
                            PostalCode = 8600,
                            Region = "Midtjylland",
                            Role = 0
                        },
                        new
                        {
                            Id = 8,
                            Address = "Parkvej 22",
                            City = "Næstved",
                            Email = "camilla.hansen@mail.com",
                            FirstName = "Camilla",
                            LastName = "Hansen",
                            Password = "$2b$12$YxbU0hgrY1aBwVsMLmVdBeScgC1rAtIc1ScvuZIS5zjzDBUyMKK9.",
                            PostalCode = 4700,
                            Region = "Sjælland",
                            Role = 0
                        },
                        new
                        {
                            Id = 9,
                            Address = "Havnevej 5",
                            City = "Hjørring",
                            Email = "rasmus.christensen@mail.com",
                            FirstName = "Rasmus",
                            LastName = "Christensen",
                            Password = "$2b$12$YxbU0hgrY1aBwVsMLmVdBeScgC1rAtIc1ScvuZIS5zjzDBUyMKK9.",
                            PostalCode = 9800,
                            Region = "Nordjylland",
                            Role = 0
                        },
                        new
                        {
                            Id = 10,
                            Address = "Torvegade 9",
                            City = "Kolding",
                            Email = "ida.jorgensen@mail.com",
                            FirstName = "Ida",
                            LastName = "Jørgensen",
                            Password = "$2b$12$YxbU0hgrY1aBwVsMLmVdBeScgC1rAtIc1ScvuZIS5zjzDBUyMKK9.",
                            PostalCode = 6000,
                            Region = "Syddanmark",
                            Role = 0
                        });
                });

            modelBuilder.Entity("IndkoebsGenieBackend.Database.Entities.GroceryList", b =>
                {
                    b.HasOne("IndkoebsGenieBackend.Database.Entities.User", "User")
                        .WithMany("GroceryLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IndkoebsGenieBackend.Database.Entities.ProductItem", b =>
                {
                    b.HasOne("IndkoebsGenieBackend.Database.Entities.GroceryList", "GroceryList")
                        .WithMany("Items")
                        .HasForeignKey("GroceryListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroceryList");
                });

            modelBuilder.Entity("IndkoebsGenieBackend.Database.Entities.GroceryList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IndkoebsGenieBackend.Database.Entities.User", b =>
                {
                    b.Navigation("GroceryLists");
                });
#pragma warning restore 612, 618
        }
    }
}
